# Argonne National Laboratory

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.runScript = QtWidgets.QPushButton(self.centralwidget)
        self.runScript.setGeometry(QtCore.QRect(580, 200, 191, 51))
        self.runScript.setStyleSheet("")
        self.runScript.setObjectName("runScript")

        self.Reset = QtWidgets.QPushButton(self.centralwidget)
        self.Reset.setGeometry(QtCore.QRect(580, 260, 191, 31))
        self.Reset.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: beige;\n"
"}")
        self.Reset.setObjectName("Reset")

        self.TimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.TimeLabel.setGeometry(QtCore.QRect(200, 130, 180, 50))
        self.TimeLabel.setStyleSheet("QLabel{font-size: 16pt;}")
        self.TimeLabel.setObjectName("TimeLabel")
        
        self.ConfidenceLabel = QtWidgets.QLabel(self.centralwidget)
        self.ConfidenceLabel.setGeometry(QtCore.QRect(410, 130, 139, 50))
        self.ConfidenceLabel.setStyleSheet("QLabel{font-size: 16pt;}")
        self.ConfidenceLabel.setObjectName("ConfidenceLabel")

        self.IDLabel = QtWidgets.QLabel(self.centralwidget)
        self.IDLabel.setGeometry(QtCore.QRect(40, 30, 161, 30))
        self.IDLabel.setStyleSheet("QLabel{font-size: 16pt;}")
        self.IDLabel.setObjectName("IDLabel")

        self.confidenceItems = QtWidgets.QComboBox(self.centralwidget)
        self.confidenceItems.setGeometry(QtCore.QRect(389, 180, 151, 31))
        self.confidenceItems.setObjectName("confidenceItems")
        self.confidenceItems.addItem("")
        self.confidenceItems.addItem("")
        self.confidenceItems.addItem("")
        self.confidenceItems.addItem("")
        self.confidenceItems.addItem("")
        self.confidenceItems.addItem("")
        self.confidenceItems.addItem("")
        self.confidenceItems.addItem("")
        self.confidenceItems.addItem("")
        self.confidenceItems.addItem("")
        self.confidenceItems.addItem("")
        self.confidenceItems.addItem("")
        self.confidenceItems.addItem("")
        self.confidenceItems.addItem("")
        self.confidenceItems.addItem("")
        self.confidenceItems.addItem("")

        self.phaseInfoLabel = QtWidgets.QLabel(self.centralwidget)
        self.phaseInfoLabel.setGeometry(QtCore.QRect(100, 440, 141, 31))
        self.phaseInfoLabel.setStyleSheet("font: 13pt \"Ubuntu\";")
        self.phaseInfoLabel.setObjectName("phaseInfoLabel")
        self.phaseInfoChange = QtWidgets.QLabel(self.centralwidget)
        self.phaseInfoChange.setGeometry(QtCore.QRect(320, 390, 431, 141))
        self.phaseInfoChange.setStyleSheet("")
        self.phaseInfoChange.setAlignment(QtCore.Qt.AlignCenter)
        self.phaseInfoChange.setObjectName("phaseInfoChange")
        self.runScript_2 = QtWidgets.QPushButton(self.centralwidget)
        self.runScript_2.setGeometry(QtCore.QRect(580, 300, 191, 51))
        self.runScript_2.setStyleSheet("")
        self.runScript_2.setObjectName("runScript_2")
        self.IDInput = QtWidgets.QLineEdit(self.centralwidget)
        self.IDInput.setGeometry(QtCore.QRect(210, 30, 141, 31))
        self.IDInput.setObjectName("IDInput")
        self.TimeInput = QtWidgets.QLineEdit(self.centralwidget)
        self.TimeInput.setGeometry(QtCore.QRect(220, 180, 130, 31))
        self.TimeInput.setObjectName("TimeInput")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 460, 211, 31))
        self.label.setStyleSheet("\n"
"font: 57 10pt \"Ubuntu\";")
        self.label.setObjectName("label")
        self.TimeInput_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.TimeInput_2.setGeometry(QtCore.QRect(221, 220, 130, 31))
        self.TimeInput_2.setObjectName("TimeInput_2")
        self.confidenceItems_2 = QtWidgets.QComboBox(self.centralwidget)
        self.confidenceItems_2.setGeometry(QtCore.QRect(390, 220, 151, 31))
        self.confidenceItems_2.setObjectName("confidenceItems_2")
        self.confidenceItems_2.addItem("")
        self.confidenceItems_2.addItem("")
        self.confidenceItems_2.addItem("")
        self.confidenceItems_2.addItem("")
        self.confidenceItems_2.addItem("")
        self.confidenceItems_2.addItem("")
        self.confidenceItems_2.addItem("")
        self.confidenceItems_2.addItem("")
        self.confidenceItems_2.addItem("")
        self.confidenceItems_2.addItem("")
        self.confidenceItems_2.addItem("")
        self.confidenceItems_2.addItem("")
        self.confidenceItems_2.addItem("")
        self.confidenceItems_2.addItem("")
        self.confidenceItems_2.addItem("")
        self.confidenceItems_2.addItem("")
        self.TimeInput_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.TimeInput_3.setGeometry(QtCore.QRect(221, 260, 130, 31))
        self.TimeInput_3.setObjectName("TimeInput_3")
        self.confidenceItems_3 = QtWidgets.QComboBox(self.centralwidget)
        self.confidenceItems_3.setGeometry(QtCore.QRect(390, 260, 151, 31))
        self.confidenceItems_3.setObjectName("confidenceItems_3")
        self.confidenceItems_3.addItem("")
        self.confidenceItems_3.addItem("")
        self.confidenceItems_3.addItem("")
        self.confidenceItems_3.addItem("")
        self.confidenceItems_3.addItem("")
        self.confidenceItems_3.addItem("")
        self.confidenceItems_3.addItem("")
        self.confidenceItems_3.addItem("")
        self.confidenceItems_3.addItem("")
        self.confidenceItems_3.addItem("")
        self.confidenceItems_3.addItem("")
        self.confidenceItems_3.addItem("")
        self.confidenceItems_3.addItem("")
        self.confidenceItems_3.addItem("")
        self.confidenceItems_3.addItem("")
        self.confidenceItems_3.addItem("")
        self.TimeInput_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.TimeInput_4.setGeometry(QtCore.QRect(221, 300, 130, 31))
        self.TimeInput_4.setObjectName("TimeInput_4")
        self.confidenceItems_4 = QtWidgets.QComboBox(self.centralwidget)
        self.confidenceItems_4.setGeometry(QtCore.QRect(390, 300, 151, 31))
        self.confidenceItems_4.setObjectName("confidenceItems_4")
        self.confidenceItems_4.addItem("")
        self.confidenceItems_4.addItem("")
        self.confidenceItems_4.addItem("")
        self.confidenceItems_4.addItem("")
        self.confidenceItems_4.addItem("")
        self.confidenceItems_4.addItem("")
        self.confidenceItems_4.addItem("")
        self.confidenceItems_4.addItem("")
        self.confidenceItems_4.addItem("")
        self.confidenceItems_4.addItem("")
        self.confidenceItems_4.addItem("")
        self.confidenceItems_4.addItem("")
        self.confidenceItems_4.addItem("")
        self.confidenceItems_4.addItem("")
        self.confidenceItems_4.addItem("")
        self.confidenceItems_4.addItem("")
        self.confidenceItems_4.addItem("")
        self.TimeInput_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.TimeInput_5.setGeometry(QtCore.QRect(221, 340, 130, 31))
        self.TimeInput_5.setObjectName("TimeInput_5")
        self.confidenceItems_5 = QtWidgets.QComboBox(self.centralwidget)
        self.confidenceItems_5.setGeometry(QtCore.QRect(390, 340, 151, 31))
        self.confidenceItems_5.setObjectName("confidenceItems_5")
        self.confidenceItems_5.addItem("")
        self.confidenceItems_5.addItem("")
        self.confidenceItems_5.addItem("")
        self.confidenceItems_5.addItem("")
        self.confidenceItems_5.addItem("")
        self.confidenceItems_5.addItem("")
        self.confidenceItems_5.addItem("")
        self.confidenceItems_5.addItem("")
        self.confidenceItems_5.addItem("")
        self.confidenceItems_5.addItem("")
        self.confidenceItems_5.addItem("")
        self.confidenceItems_5.addItem("")
        self.confidenceItems_5.addItem("")
        self.confidenceItems_5.addItem("")
        self.confidenceItems_5.addItem("")
        self.confidenceItems_5.addItem("")
        self.confidenceItems_5.addItem("")
        self.PhaseItem = QtWidgets.QComboBox(self.centralwidget)
        self.PhaseItem.setGeometry(QtCore.QRect(30, 180, 151, 31))
        self.PhaseItem.setObjectName("PhaseItem")
        self.PhaseItem.addItem("")
        self.PhaseItem.addItem("")
        self.PhaseItem.addItem("")
        self.PhaseItem.addItem("")
        self.PhaseItem.addItem("")
        self.PhaseItem.addItem("")
        self.PhaseItem.addItem("")
        self.PhaseItem.addItem("")
        self.PhaseItem.addItem("")
        self.PhaseItem.addItem("")
        self.PhaseItem_2 = QtWidgets.QComboBox(self.centralwidget)
        self.PhaseItem_2.setGeometry(QtCore.QRect(30, 220, 151, 31))
        self.PhaseItem_2.setObjectName("PhaseItem_2")
        self.PhaseItem_2.addItem("")
        self.PhaseItem_2.addItem("")
        self.PhaseItem_2.addItem("")
        self.PhaseItem_2.addItem("")
        self.PhaseItem_2.addItem("")
        self.PhaseItem_2.addItem("")
        self.PhaseItem_2.addItem("")
        self.PhaseItem_2.addItem("")
        self.PhaseItem_2.addItem("")
        self.PhaseItem_2.addItem("")
        self.PhaseItem_3 = QtWidgets.QComboBox(self.centralwidget)
        self.PhaseItem_3.setGeometry(QtCore.QRect(30, 260, 151, 31))
        self.PhaseItem_3.setObjectName("PhaseItem_3")
        self.PhaseItem_3.addItem("")
        self.PhaseItem_3.addItem("")
        self.PhaseItem_3.addItem("")
        self.PhaseItem_3.addItem("")
        self.PhaseItem_3.addItem("")
        self.PhaseItem_3.addItem("")
        self.PhaseItem_3.addItem("")
        self.PhaseItem_3.addItem("")
        self.PhaseItem_3.addItem("")
        self.PhaseItem_3.addItem("")
        self.PhaseItem_4 = QtWidgets.QComboBox(self.centralwidget)
        self.PhaseItem_4.setGeometry(QtCore.QRect(30, 300, 151, 31))
        self.PhaseItem_4.setObjectName("PhaseItem_4")
        self.PhaseItem_4.addItem("")
        self.PhaseItem_4.addItem("")
        self.PhaseItem_4.addItem("")
        self.PhaseItem_4.addItem("")
        self.PhaseItem_4.addItem("")
        self.PhaseItem_4.addItem("")
        self.PhaseItem_4.addItem("")
        self.PhaseItem_4.addItem("")
        self.PhaseItem_4.addItem("")
        self.PhaseItem_4.addItem("")
        self.PhaseItem_4.addItem("")
        self.PhaseItem_5 = QtWidgets.QComboBox(self.centralwidget)
        self.PhaseItem_5.setGeometry(QtCore.QRect(30, 340, 151, 31))
        self.PhaseItem_5.setObjectName("PhaseItem_5")
        self.PhaseItem_5.addItem("")
        self.PhaseItem_5.addItem("")
        self.PhaseItem_5.addItem("")
        self.PhaseItem_5.addItem("")
        self.PhaseItem_5.addItem("")
        self.PhaseItem_5.addItem("")
        self.PhaseItem_5.addItem("")
        self.PhaseItem_5.addItem("")
        self.PhaseItem_5.addItem("")
        self.PhaseItem_5.addItem("")
        self.PhaseItem_5.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 140, 67, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 79, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 80, 141, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(590, 30, 170, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 29, 160, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(410, 80, 160, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(590, 81, 170, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(380, 110, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuUI_for_SPaT_Creation = QtWidgets.QMenu(self.menubar)
        self.menuUI_for_SPaT_Creation.setObjectName("menuUI_for_SPaT_Creation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuUI_for_SPaT_Creation.menuAction())

        #SIGNALS AND SLOTS
        self.retranslateUi(MainWindow)
        
        # self.confidenceItems.setCurrentIndex(15)
        # self.Reset.clicked.connect(self.listWidget.clearSelection)
        # self.listWidget.clicked['QModelIndex'].connect(self.phaseInfoChange.setFocus)
        # self.listWidget.doubleClicked['QModelIndex'].connect(self.phaseInfoChange.show)
        # self.Reset.clicked.connect(self.phaseInfoChange.update)

        self.confidenceItems.setCurrentIndex(15)
        self.Reset.clicked.connect(self.IDInput.clear)
        self.Reset.clicked.connect(lambda: self.confidenceItems.setCurrentIndex(15))
        self.Reset.clicked.connect(self.TimeInput.clear)
        self.Reset.clicked.connect(lambda: self.phaseInfoChange.setText("Select an option!"))

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Mess with this for SIGNAL INFORMATION
    def onClicked(self, item):
        if(item.text() == "unavailable (0)"):
            self.phaseInfoChange.setText("set description here0")

        elif(item.text() == "dark (1)"):
            self.phaseInfoChange.setText("set description here1")

        elif(item.text() == "stop-Then-Proceed (2)"):
            self.phaseInfoChange.setText("set description here2")

        elif(item.text() == "stop-And-Remain (3)"):
            self.phaseInfoChange.setText("-- e.g. called 'red light' in US\n-- Driver Action:\n- Stop vehicle at stop line.\n- Do not proceed.\n-- Note that the right to proceed either right or left when\nit is safe may be contained in the\nlane description to handle what is called a 'right on red'")
    
        elif(item.text() == "pre-Movement (4)"):
            self.phaseInfoChange.setText("set description here4")

        elif(item.text() == "permissive-Movement-Allowed (5)"):
            self.phaseInfoChange.setText("set description here5")

        elif(item.text() == "protected-Movement-Allowed (6)"):
            self.phaseInfoChange.setText("set description here6")

        elif(item.text() == "permissive-clearance (7)"):
            self.phaseInfoChange.setText("set description here7")

        elif(item.text() == "protected-clearance (8)"):
            self.phaseInfoChange.setText("set description here8")

        elif(item.text() == "caution-Conflicting-Traffic (9)"):
            self.phaseInfoChange.setText("set description here9")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.runScript.setText(_translate("MainWindow", "Create SPATs"))
        self.Reset.setText(_translate("MainWindow", "RESET"))
        self.TimeLabel.setText(_translate("MainWindow", "Time (in seconds):"))
        self.ConfidenceLabel.setText(_translate("MainWindow", "Confidence:"))
        self.IDLabel.setText(_translate("MainWindow", "Intersection ID:"))
        self.confidenceItems.setItemText(0, _translate("MainWindow", "0 (21%)"))
        self.confidenceItems.setItemText(1, _translate("MainWindow", "1 (36%)"))
        self.confidenceItems.setItemText(2, _translate("MainWindow", "2 (47%)"))
        self.confidenceItems.setItemText(3, _translate("MainWindow", "3 (56%)"))
        self.confidenceItems.setItemText(4, _translate("MainWindow", "4 (62%)"))
        self.confidenceItems.setItemText(5, _translate("MainWindow", "5 (68%)"))
        self.confidenceItems.setItemText(6, _translate("MainWindow", "6 (73%)"))
        self.confidenceItems.setItemText(7, _translate("MainWindow", "7 (77%)"))
        self.confidenceItems.setItemText(8, _translate("MainWindow", "8 (81%)"))
        self.confidenceItems.setItemText(9, _translate("MainWindow", "9 (85%)"))
        self.confidenceItems.setItemText(10, _translate("MainWindow", "10 (88%)"))
        self.confidenceItems.setItemText(11, _translate("MainWindow", "11 (91%)"))
        self.confidenceItems.setItemText(12, _translate("MainWindow", "12 (94%)"))
        self.confidenceItems.setItemText(13, _translate("MainWindow", "13 (96%)"))
        self.confidenceItems.setItemText(14, _translate("MainWindow", "14 (98%)"))
        self.confidenceItems.setItemText(15, _translate("MainWindow", "15 (100%)"))
        self.phaseInfoLabel.setText(_translate("MainWindow", "Phase information"))
        self.phaseInfoChange.setText(_translate("MainWindow", "Select a Phase!"))
        self.runScript_2.setText(_translate("MainWindow", "Transmit SPATs"))
        self.label.setText(_translate("MainWindow", "Double tap on a phase to see more!"))
        self.confidenceItems_2.setItemText(0, _translate("MainWindow", "0 (21%)"))
        self.confidenceItems_2.setItemText(1, _translate("MainWindow", "1 (36%)"))
        self.confidenceItems_2.setItemText(2, _translate("MainWindow", "2 (47%)"))
        self.confidenceItems_2.setItemText(3, _translate("MainWindow", "3 (56%)"))
        self.confidenceItems_2.setItemText(4, _translate("MainWindow", "4 (62%)"))
        self.confidenceItems_2.setItemText(5, _translate("MainWindow", "5 (68%)"))
        self.confidenceItems_2.setItemText(6, _translate("MainWindow", "6 (73%)"))
        self.confidenceItems_2.setItemText(7, _translate("MainWindow", "7 (77%)"))
        self.confidenceItems_2.setItemText(8, _translate("MainWindow", "8 (81%)"))
        self.confidenceItems_2.setItemText(9, _translate("MainWindow", "9 (85%)"))
        self.confidenceItems_2.setItemText(10, _translate("MainWindow", "10 (88%)"))
        self.confidenceItems_2.setItemText(11, _translate("MainWindow", "11 (91%)"))
        self.confidenceItems_2.setItemText(12, _translate("MainWindow", "12 (94%)"))
        self.confidenceItems_2.setItemText(13, _translate("MainWindow", "13 (96%)"))
        self.confidenceItems_2.setItemText(14, _translate("MainWindow", "14 (98%)"))
        self.confidenceItems_2.setItemText(15, _translate("MainWindow", "15 (100%)"))
        self.confidenceItems_3.setItemText(0, _translate("MainWindow", "0 (21%)"))
        self.confidenceItems_3.setItemText(1, _translate("MainWindow", "1 (36%)"))
        self.confidenceItems_3.setItemText(2, _translate("MainWindow", "2 (47%)"))
        self.confidenceItems_3.setItemText(3, _translate("MainWindow", "3 (56%)"))
        self.confidenceItems_3.setItemText(4, _translate("MainWindow", "4 (62%)"))
        self.confidenceItems_3.setItemText(5, _translate("MainWindow", "5 (68%)"))
        self.confidenceItems_3.setItemText(6, _translate("MainWindow", "6 (73%)"))
        self.confidenceItems_3.setItemText(7, _translate("MainWindow", "7 (77%)"))
        self.confidenceItems_3.setItemText(8, _translate("MainWindow", "8 (81%)"))
        self.confidenceItems_3.setItemText(9, _translate("MainWindow", "9 (85%)"))
        self.confidenceItems_3.setItemText(10, _translate("MainWindow", "10 (88%)"))
        self.confidenceItems_3.setItemText(11, _translate("MainWindow", "11 (91%)"))
        self.confidenceItems_3.setItemText(12, _translate("MainWindow", "12 (94%)"))
        self.confidenceItems_3.setItemText(13, _translate("MainWindow", "13 (96%)"))
        self.confidenceItems_3.setItemText(14, _translate("MainWindow", "14 (98%)"))
        self.confidenceItems_3.setItemText(15, _translate("MainWindow", "15 (100%)"))
        self.confidenceItems_4.setItemText(0, _translate("MainWindow", "select an option"))
        self.confidenceItems_4.setItemText(1, _translate("MainWindow", "0 (21%)"))
        self.confidenceItems_4.setItemText(2, _translate("MainWindow", "1 (36%)"))
        self.confidenceItems_4.setItemText(3, _translate("MainWindow", "2 (47%)"))
        self.confidenceItems_4.setItemText(4, _translate("MainWindow", "3 (56%)"))
        self.confidenceItems_4.setItemText(5, _translate("MainWindow", "4 (62%)"))
        self.confidenceItems_4.setItemText(6, _translate("MainWindow", "5 (68%)"))
        self.confidenceItems_4.setItemText(7, _translate("MainWindow", "6 (73%)"))
        self.confidenceItems_4.setItemText(8, _translate("MainWindow", "7 (77%)"))
        self.confidenceItems_4.setItemText(9, _translate("MainWindow", "8 (81%)"))
        self.confidenceItems_4.setItemText(10, _translate("MainWindow", "9 (85%)"))
        self.confidenceItems_4.setItemText(11, _translate("MainWindow", "10 (88%)"))
        self.confidenceItems_4.setItemText(12, _translate("MainWindow", "11 (91%)"))
        self.confidenceItems_4.setItemText(13, _translate("MainWindow", "12 (94%)"))
        self.confidenceItems_4.setItemText(14, _translate("MainWindow", "13 (96%)"))
        self.confidenceItems_4.setItemText(15, _translate("MainWindow", "14 (98%)"))
        self.confidenceItems_4.setItemText(16, _translate("MainWindow", "15 (100%)"))
        self.confidenceItems_5.setItemText(0, _translate("MainWindow", "select an option"))
        self.confidenceItems_5.setItemText(1, _translate("MainWindow", "0 (21%)"))
        self.confidenceItems_5.setItemText(2, _translate("MainWindow", "1 (36%)"))
        self.confidenceItems_5.setItemText(3, _translate("MainWindow", "2 (47%)"))
        self.confidenceItems_5.setItemText(4, _translate("MainWindow", "3 (56%)"))
        self.confidenceItems_5.setItemText(5, _translate("MainWindow", "4 (62%)"))
        self.confidenceItems_5.setItemText(6, _translate("MainWindow", "5 (68%)"))
        self.confidenceItems_5.setItemText(7, _translate("MainWindow", "6 (73%)"))
        self.confidenceItems_5.setItemText(8, _translate("MainWindow", "7 (77%)"))
        self.confidenceItems_5.setItemText(9, _translate("MainWindow", "8 (81%)"))
        self.confidenceItems_5.setItemText(10, _translate("MainWindow", "9 (85%)"))
        self.confidenceItems_5.setItemText(11, _translate("MainWindow", "10 (88%)"))
        self.confidenceItems_5.setItemText(12, _translate("MainWindow", "11 (91%)"))
        self.confidenceItems_5.setItemText(13, _translate("MainWindow", "12 (94%)"))
        self.confidenceItems_5.setItemText(14, _translate("MainWindow", "13 (96%)"))
        self.confidenceItems_5.setItemText(15, _translate("MainWindow", "14 (98%)"))
        self.confidenceItems_5.setItemText(16, _translate("MainWindow", "15 (100%)"))
        self.PhaseItem.setItemText(0, _translate("MainWindow", "unavailable (0)"))
        self.PhaseItem.setItemText(1, _translate("MainWindow", "dark (1)"))
        self.PhaseItem.setItemText(2, _translate("MainWindow", "stop-Then-Proceed (2)"))
        self.PhaseItem.setItemText(3, _translate("MainWindow", "stop-And-Remain (3)"))
        self.PhaseItem.setItemText(4, _translate("MainWindow", "pre-Movement (4)"))
        self.PhaseItem.setItemText(5, _translate("MainWindow", "permissive-Movement-Allowed (5)"))
        self.PhaseItem.setItemText(6, _translate("MainWindow", "protected-Movement-Allowed (6)"))
        self.PhaseItem.setItemText(7, _translate("MainWindow", "permissive-clearance (7)"))
        self.PhaseItem.setItemText(8, _translate("MainWindow", "protected-clearance (8)"))
        self.PhaseItem.setItemText(9, _translate("MainWindow", "caution-Conflicting-Traffic (9)"))
        self.PhaseItem_2.setItemText(0, _translate("MainWindow", "unavailable (0)"))
        self.PhaseItem_2.setItemText(1, _translate("MainWindow", "dark (1)"))
        self.PhaseItem_2.setItemText(2, _translate("MainWindow", "stop-Then-Proceed (2)"))
        self.PhaseItem_2.setItemText(3, _translate("MainWindow", "stop-And-Remain (3)"))
        self.PhaseItem_2.setItemText(4, _translate("MainWindow", "pre-Movement (4)"))
        self.PhaseItem_2.setItemText(5, _translate("MainWindow", "permissive-Movement-Allowed (5)"))
        self.PhaseItem_2.setItemText(6, _translate("MainWindow", "protected-Movement-Allowed (6)"))
        self.PhaseItem_2.setItemText(7, _translate("MainWindow", "permissive-clearance (7)"))
        self.PhaseItem_2.setItemText(8, _translate("MainWindow", "protected-clearance (8)"))
        self.PhaseItem_2.setItemText(9, _translate("MainWindow", "caution-Conflicting-Traffic (9)"))
        self.PhaseItem_3.setItemText(0, _translate("MainWindow", "unavailable (0)"))
        self.PhaseItem_3.setItemText(1, _translate("MainWindow", "dark (1)"))
        self.PhaseItem_3.setItemText(2, _translate("MainWindow", "stop-Then-Proceed (2)"))
        self.PhaseItem_3.setItemText(3, _translate("MainWindow", "stop-And-Remain (3)"))
        self.PhaseItem_3.setItemText(4, _translate("MainWindow", "pre-Movement (4)"))
        self.PhaseItem_3.setItemText(5, _translate("MainWindow", "permissive-Movement-Allowed (5)"))
        self.PhaseItem_3.setItemText(6, _translate("MainWindow", "protected-Movement-Allowed (6)"))
        self.PhaseItem_3.setItemText(7, _translate("MainWindow", "permissive-clearance (7)"))
        self.PhaseItem_3.setItemText(8, _translate("MainWindow", "protected-clearance (8)"))
        self.PhaseItem_3.setItemText(9, _translate("MainWindow", "caution-Conflicting-Traffic (9)"))
        self.PhaseItem_4.setItemText(0, _translate("MainWindow", "select an option"))
        self.PhaseItem_4.setItemText(1, _translate("MainWindow", "unavailable (0)"))
        self.PhaseItem_4.setItemText(2, _translate("MainWindow", "dark (1)"))
        self.PhaseItem_4.setItemText(3, _translate("MainWindow", "stop-Then-Proceed (2)"))
        self.PhaseItem_4.setItemText(4, _translate("MainWindow", "stop-And-Remain (3)"))
        self.PhaseItem_4.setItemText(5, _translate("MainWindow", "pre-Movement (4)"))
        self.PhaseItem_4.setItemText(6, _translate("MainWindow", "permissive-Movement-Allowed (5)"))
        self.PhaseItem_4.setItemText(7, _translate("MainWindow", "protected-Movement-Allowed (6)"))
        self.PhaseItem_4.setItemText(8, _translate("MainWindow", "permissive-clearance (7)"))
        self.PhaseItem_4.setItemText(9, _translate("MainWindow", "protected-clearance (8)"))
        self.PhaseItem_4.setItemText(10, _translate("MainWindow", "caution-Conflicting-Traffic (9)"))
        self.PhaseItem_5.setItemText(0, _translate("MainWindow", "select an option"))
        self.PhaseItem_5.setItemText(1, _translate("MainWindow", "unavailable (0)"))
        self.PhaseItem_5.setItemText(2, _translate("MainWindow", "dark (1)"))
        self.PhaseItem_5.setItemText(3, _translate("MainWindow", "stop-Then-Proceed (2)"))
        self.PhaseItem_5.setItemText(4, _translate("MainWindow", "stop-And-Remain (3)"))
        self.PhaseItem_5.setItemText(5, _translate("MainWindow", "pre-Movement (4)"))
        self.PhaseItem_5.setItemText(6, _translate("MainWindow", "permissive-Movement-Allowed (5)"))
        self.PhaseItem_5.setItemText(7, _translate("MainWindow", "protected-Movement-Allowed (6)"))
        self.PhaseItem_5.setItemText(8, _translate("MainWindow", "permissive-clearance (7)"))
        self.PhaseItem_5.setItemText(9, _translate("MainWindow", "protected-clearance (8)"))
        self.PhaseItem_5.setItemText(10, _translate("MainWindow", "caution-Conflicting-Traffic (9)"))
        self.label_2.setText(_translate("MainWindow", "Phase:"))
        self.label_3.setText(_translate("MainWindow", "Signal Group ID:"))
        self.label_4.setText(_translate("MainWindow", "RSU IP Address:"))
        self.label_5.setText(_translate("MainWindow", "Text file name:"))
        self.label_6.setText(_translate("MainWindow", "creates SPAT.txt if name not specified"))
        self.menuUI_for_SPaT_Creation.setTitle(_translate("MainWindow", "UI for SPaT Creation"))

# Main Method
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    w = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(w)
    w.show()
    sys.exit(app.exec_())

    '''

# Main Method
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    w = QtWidgets.QMainWindow()
    ui = Ui_UIWindowSPaTGenerator()
    ui.setupUi(w)
    w.show()
    sys.exit(app.exec_())

        self.retranslateUi(UIWindowSPaTGenerator)
        self.confidenceItem1.setCurrentIndex(15)
        self.confidenceItem2.setCurrentIndex(15)
        self.confidenceItem3.setCurrentIndex(15)
        self.clearFieldsButton.clicked.connect(lambda: self.confidenceItem1.setCurrentIndex(15))
        self.clearFieldsButton.clicked.connect(lambda: self.confidenceItem2.setCurrentIndex(15))
        self.clearFieldsButton.clicked.connect(lambda: self.confidenceItem3.setCurrentIndex(15))
        self.clearFieldsButton.clicked.connect(lambda: self.confidenceItem4.setCurrentIndex(0))
        self.clearFieldsButton.clicked.connect(lambda: self.confidenceItem5.setCurrentIndex(0))
        self.clearFieldsButton.clicked.connect(lambda: self.phaseItem1.setCurrentIndex(0))
        self.clearFieldsButton.clicked.connect(lambda: self.phaseItem2.setCurrentIndex(0))
        self.clearFieldsButton.clicked.connect(lambda: self.phaseItem3.setCurrentIndex(0))
        self.clearFieldsButton.clicked.connect(lambda: self.phaseItem4.setCurrentIndex(0))
        self.clearFieldsButton.clicked.connect(lambda: self.phaseItem5.setCurrentIndex(0))

'''